src/Entity/Articel.php
<?php

namespace App\Entity;

use App\Repository\ArticelRepository;
use App\Service\UploaderHelper;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JetBrains\PhpStorm\Pure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @ORM\Entity(repositoryClass=ArticelRepository::class)
 */
class Articel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titel;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $kurztext;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $haupttext;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bild;

    /**
     * @ORM\Column(type="integer")
     */
    private $views = 0;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $datum;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Gedmo\Slug(fields={"titel"})
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Themen::class, inversedBy="articels")
     */
    private $thema;

    /**
     * @ORM\OneToMany(targetEntity=ArtikelBilder::class, mappedBy="artikel", orphanRemoval=true)
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $artikelBilders;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $top;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $extra = [];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $oldId;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articels")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="articel")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=ArtikelMitwirkungen::class, mappedBy="artikel")
     */
    private $artikelMitwirkungens;

    public function __construct()
    {
        $this->artikelBilders = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->artikelMitwirkungens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitel(): ?string
    {
        return $this->titel;
    }

    public function setTitel(string $titel): self
    {
        $this->titel = $titel;

        return $this;
    }

    public function getCreateAt(): ?DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getKurztext(): ?string
    {
        return $this->kurztext;
    }

    public function setKurztext(?string $kurztext): self
    {
        $this->kurztext = $kurztext;

        return $this;
    }

    public function getHaupttext(): ?string
    {
        return $this->haupttext;
    }

    public function setHaupttext(?string $haupttext): self
    {
        $this->haupttext = $haupttext;

        return $this;
    }

    public function getBild(): ?string
    {
        return $this->bild;
    }

    public function setBild(?string $bild): self
    {
        $this->bild = $bild;

        return $this;
    }

    #[Pure] public function getImagePath(): ?string
    {
        return '/uploads/'.UploaderHelper::ARTIKEL_IMAGE.'/'.$this->getBild();
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getDatum(): ?DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(?DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getThema(): ?Themen
    {
        return $this->thema;
    }

    public function setThema(?Themen $thema): self
    {
        $this->thema = $thema;

        return $this;
    }

    /**
     * @return Collection|ArtikelBilder[]
     */
    public function getArtikelBilders(): Collection
    {
        return $this->artikelBilders;
    }

    public function addArtikelBilder(ArtikelBilder $artikelBilder): self
    {
        if (!$this->artikelBilders->contains($artikelBilder)) {
            $this->artikelBilders[] = $artikelBilder;
            $artikelBilder->setArtikel($this);
        }

        return $this;
    }

    public function removeArtikelBilder(ArtikelBilder $artikelBilder): self
    {
        if ($this->artikelBilders->removeElement($artikelBilder)) {
            // set the owning side to null (unless already changed)
            if ($artikelBilder->getArtikel() === $this) {
                $artikelBilder->setArtikel(null);
            }
        }

        return $this;
    }

    public function getTop(): ?bool
    {
        return $this->top;
    }

    public function setTop(?bool $top): self
    {
        $this->top = $top;

        return $this;
    }

    public function getExtra(): ?array
    {
        return $this->extra;
    }

    public function setExtra(?array $extra): self
    {
        $this->extra = $extra;

        return $this;
    }

    public function addExtra(?array $extra): self
    {
        $extras = $this->getExtra();
        if (!in_array($extra, $extras)){
            array_push($extras, $extra);
        }

        return $this;
    }

    public function getOldId(): ?int
    {
        return $this->oldId;
    }

    public function setOldId(?int $oldId): self
    {
        $this->oldId = $oldId;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticel($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticel() === $this) {
                $comment->setArticel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArtikelMitwirkungen[]
     */
    public function getArtikelMitwirkungens(): Collection
    {
        return $this->artikelMitwirkungens;
    }

    public function addArtikelMitwirkungen(ArtikelMitwirkungen $artikelMitwirkungen): self
    {
        if (!$this->artikelMitwirkungens->contains($artikelMitwirkungen)) {
            $this->artikelMitwirkungens[] = $artikelMitwirkungen;
            $artikelMitwirkungen->setArtikel($this);
        }

        return $this;
    }

    public function removeArtikelMitwirkungen(ArtikelMitwirkungen $artikelMitwirkungen): self
    {
        if ($this->artikelMitwirkungens->removeElement($artikelMitwirkungen)) {
            // set the owning side to null (unless already changed)
            if ($artikelMitwirkungen->getArtikel() === $this) {
                $artikelMitwirkungen->setArtikel(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Articel::class, mappedBy="author")
     */
    private $articels;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="author")
     */
    private $comments;

    /**
     * @ORM\OneToOne(targetEntity=Personen::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $personen;

    public function __construct()
    {
        $this->articels = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getArticels(): Collection
    {
        return $this->articels;
    }

    public function addArticel(Articel $articel): self
    {
        if (!$this->articels->contains($articel)) {
            $this->articels[] = $articel;
            $articel->setAuthor($this);
        }

        return $this;
    }

    public function removeArticel(Articel $articel): self
    {
        if ($this->articels->removeElement($articel)) {
            // set the owning side to null (unless already changed)
            if ($articel->getAuthor() === $this) {
                $articel->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function getPersonen(): ?Personen
    {
        return $this->personen;
    }

    public function setPersonen(?Personen $personen): self
    {
        // unset the owning side of the relation if necessary
        if ($personen === null && $this->personen !== null) {
            $this->personen->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($personen !== null && $personen->getUser() !== $this) {
            $personen->setUser($this);
        }

        $this->personen = $personen;

        return $this;
    }
}

templates/_card-spinner.html.twig
<div class="card widget-card-red">
    <div class="card-body p-3 mt-1">
        <div class="d-flex justify-content-center m-2">
            <div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
</div>

templates/_modal.html.twig
<div
        class="modal fade"
        tabindex="-1"
        aria-hidden="true"
        data-modal-form-target="modal"
>
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel" data-modal-form-target="modalTitel">
                    <i class="fa fa-1x fa-spin fa-spinner"></i>
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div
                    class="modal-body"
                    data-modal-form-target="modalBody"
                    data-action="submit->#submitForm"
            >
                {{ modalContent|default('<i class="fa fa-2x fa-spin fa-spinner"></i>') }}
            </div>
            <div class="modal-footer bg-white-20">
                <button
                        type="button"
                        class="btn btn-secondary"
                        data-bs-dismiss="modal"
                        data-modal-form-target="caclBtn"
                >
                    Abbruch
                </button>
                <button
                        type="button"
                        class="btn btn-success"
                        data-action="modal-form#submitForm"
                        data-modal-form-target="okBtn"
                >
                    Speichern
                </button>
            </div>
        </div>
    </div>
</div>

templates/_tanken-card.html.twig
<turbo-frame id="tankstellen" >
<div class="card my-2" {{ stimulus_controller('tanker') }}>
    <div class="card-header d-flex justify-content-end overflow-hidden">
        Tank-Preise
    </div>
    <div class="card-body py-1">
        <div class="row">
            <div class="col-9">
                <label for="customRange3" class="form-label">Umkreis</label>
                <input type="range" class="form-range" min="5" max="25" step="1" value="{{ radius }}" id="customRange3" {{ stimulus_target('tanker', 'rangeSlider') }} data-action="change->tanker#valuechange">
            </div>
            <div class="col-3">
                <label for="form-ange" class="form-label">KM</label>
                <input type="text" class="form-range" id="form-range" readonly value="{{ radius }}" {{ stimulus_target('tanker', 'rangeInput') }} >
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Diesel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">E5</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">E10</a>
                    </li>
                </ul>
            </div>
        </div>
        {% for tankstelle in tankstellen %}
        <div class="row">
            <div class="col-12 bg-light border-top mt-3">
                {{ tankstelle.name }} - {{ tankstelle.place }}
            </div>
            <div class="col-3">
                {% if tankstelle.brand == 'Shell' %}
                <img src="{{ asset('build/images/logos/shell.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'ESSO' %}
                    <img src="{{ asset('build/images/logos/esso.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'JET' %}
                    <img src="{{ asset('build/images/logos/jet.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'Freie Tankstelle' %}
                    <img src="{{ asset('build/images/logos/freie_t.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'freie Tankstelle' %}
                    <img src="{{ asset('build/images/logos/freie_t.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'KÖHN & PLAMBECK' %}
                    <img src="{{ asset('build/images/logos/Tankkarte-1.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}

                {% if tankstelle.brand == 'JOISS' %}
                    <img src="{{ asset('build/images/logos/joiss.png')|imagine_filter('squared_logo_nano') }}" alt="logo" />
                {% endif %}
            </div>
            <div class="col-9">
                <small>{{ tankstelle.diesel }} €</small>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</turbo-frame>

templates/base.html.twig
<!DOCTYPE html>
<html lang="de" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Jörg Timm">
        <!-- Favicon -->
    {% block style %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}

    <title>{% block title %}Uthlede!{% endblock %}</title>
    </head>
    <body>
    {% block body %}
        <div class="container">
            <header class="blog-header bg-green py-0">
                <div class="row flex-nowrap justify-content-between align-items-center bg-green p-2">
                    <div class="col-auto pt-1">
                        <a class="link-secondary" href="{{ path('app_home') }}" aria-label="Logo">
                            <img src="{{ asset('/build/images/wappen_uthlede.png')|imagine_filter('squared_thumbnail_mini') }}" alt="wappen-von-uthlede"/>
                        </a>
                    </div>
                    <div class="d-none d-sm-none d-md-block col-md-4 col-lg-4 text-center">
                        <a class="blog-header-logo text-dark" href="{{ path('app_home') }}">UTHLEDE.DE </a>
                    </div>
                    <div class="col-4 d-flex justify-content-end align-items-center">
                        {#
                        <a class="link-secondary" href="#" aria-label="Search">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
                        </a>
                        #}
                        {% if is_granted('ROLE_ADMIN') %}
                            <a class="btn btn-sm btn-outline-secondary mx-1" href="{{ path('admin:dashboard') }}" target="_top"><i class="fa fa-dashboard me-2"></i>Admin</a>
                        {% endif %}
                        {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                            <a class="btn btn-sm btn-outline-secondary mx-1" href="{{ path('app_logout') }}" target="_top"><i class="fa fa-user-circle-o me-2"></i> {{ app.user.userIdentifier }}</a>
                        {% else %}
                        <a class="btn btn-sm btn-outline-secondary mx-1" href="{{ path('app_login') }}" target="_top">
                            <i class="fa fa-sign-in me-2"></i>
                            Login
                        </a>
                        <a class="btn btn-sm btn-outline-secondary mx-1" href="{{ path('app_register') }}" target="_top">
                            <i class="fa fa-user-plus me-2"></i>
                            Registrieren
                        </a>
                        {% endif %}
                    </div>
                </div>
            </header>
            <nav class="navbar navbar-expand-md navbar-light bg-light mb-3">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_home') }}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_artikel_list') }}">Berichte</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Das Dorf</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Vereine</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Historisch</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <main class="container">
    {% block content %}
            {#
            <div class="p-4 p-md-5 mb-4 text-white rounded main-storry">
                <div class="col-md-6 px-0">
                    <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
                    <p class="lead my-3">Multiple lines of text that form the lede, informing vcbvcbvnew readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
                    <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
                </div>
            </div>
            #}
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-8">
                    <turbo-frame id="articel-list-{{ pager.currentPage }}">
                    <div class="row">
                        {% for artikel in pager %}
                            <div class="card news-card mb-3">
                                <div class="row g-0">
                                    <div class="col-md-4">
                                        <a href="{{ path('app_artikel_view', { slug: artikel.slug }) }}">
                                            <img src="{{ artikel.imagePath|imagine_filter('squared_thumbnail_min_ob') }}" class="img-fluid" alt="...">
                                        </a>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <a href="{{ path('app_artikel_view', { slug: artikel.slug }) }}">
                                            <h5 class="card-title">{{ artikel.titel }}</h5>
                                            </a>
                                            <p class="card-text d-flex justify-start">
                                                <small class="text-muted mx-1"><i class="fa fa-calendar-o me-1"></i>{{ artikel.datum|date('d.m.Y') }}</small>
                                                {% for mitwirker in artikel.artikelMitwirkungens %}
                                                    {% if mitwirker.art == 'Author' %}
                                                        <a href="#">
                                                            <small class="text-muted mx-1">
                                                                <i class="fa fa-user me-1"></i>{{ mitwirker.person.vorname }} {{ mitwirker.person.name }}
                                                            </small>
                                                        </a>
                                                    {% endif %}
                                                {% endfor %}
                                                <a href="#">
                                                    <small class="text-muted mx-1"><i class="fa fa-folder me-1"></i>{{ artikel.thema.titel }}</small>
                                                </a>

                                            </p>
                                            <p class="card-text">{{ artikel.haupttext|truncate(100)|raw }}</p>
                                            <p class="card-text">
                                                <a class="link-secondary" href="{{ path('app_artikel_view', { slug: artikel.slug }) }}">
                                                    Weiter lesen ...
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% if pager.hasNextPage %}
                            <turbo-frame id="articel-list-{{ pager.nextPage }}" src="{{ pagerfanta_page_url(pager, pager.nextPage) }}" loading="lazy">
                                {{ include('_card-spinner.html.twig') }}
                            </turbo-frame>
                        {% endif %}
                    </div>
                    </turbo-frame>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-4" >
                    <turbo-frame id="tankstellen" src="{{ fragment_uri(controller('App\\Controller\\HomeController::tankstellenAbfrage')) }}" loading="lazy">
                        {{ include('_card-spinner.html.twig') }}
                    </turbo-frame>
                    {{ component('wetter') }}

                    <div class="p-1 mb-3 bg-light rounded">
                        <form>
                            <div
                                    class="input-group"
                                    {{ stimulus_controller('autocomplete') }}
                                    data-autocomplete-url-value="{{ path('app_artikel_list', { preview: 1 }) }}"
                            >
                                <input type="hidden" name="id" data-autocomplete-target="hidden"/>
                                <input
                                        name="q"
                                        placeholder="Suche..."
                                        type="text"
                                        class="form-control"
                                        data-autocomplete-target="input"
                                >

                                <div
                                        class="list-group search-preview overflow-auto"
                                        data-autocomplete-target="results"
                                >

                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="p-1">
                        <h4 class="text-center">Themen</h4>
                        <hr/>
                        <ul class="list-group">
                            {% for thema in themen %}
                                <a href="{{ path('app_artikel_list', {
                                    t: thema.id
                                }) }}">
                                    <li class="list-group-item d-flex justify-content-between align-items-start">
                                        <div class="ms-2 me-auto">
                                            <div class="fw-bold link-main overflow-hidden">{{ thema.titel }}</div>
                                        </div>
                                        <span class="badge bg-success rounded-pill">{{ thema.artikelanzahl }}</span>
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div><!-- /.row -->
        {% endblock %}
        </main><!-- /.container -->
        <footer class="footer container bg-green text-light my-3" {{ stimulus_controller('tanker') }}>
            <div class="row mb-3">
                <div class="col-sm-12 col-md-6 col-lg-4 p-2">
                    <h4>Uthlede.de</h4>
                    <hr>
                    <p class="ms-3 mb-2">Redaktion: Otto Baur</p>
                    <p class="ms-3 mb-2">Moderatorin: Conny Trowitzsch</p>
                    <p class="ms-3 mb-2">Administrator: Jörg Timm</p>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4 p-2">
                    <h4>Kontakt</h4>
                    <hr>
                    <p class="ms-3 mb-2">Uthlede</p>
                    <p class="ms-3 mb-2">Bürgermeister</p>
                    <p class="ms-3 mb-2">Kontakt</p>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4 p-2">
                    <h4>Rechtlich</h4>
                    <hr>
                    <p class="ms-3 mb-2">Impreessum</p>
                    <p class="ms-3 mb-2">Datenschutz</p>
                </div>
            </div>
        </footer>
    {% endblock %}
    </body>
</html>